### ISSUE TITLE
Support Ext.require

### ISSUE THREAD

**Issue by wrumsby** [cpak/grunt-extjs-dependencies#5]
It seems that this task only looks for `requires` as part of the configuration object passed to `Ext.define`, but not [`Ext.require`](http://docs.sencha.com/extjs/4.2.0/#!/api/Ext-method-require). This means that I can't use this task with code written like this:

```
Ext.require([...], function () {
    // some share state that comes in from the require
    var a = ...;

    Ext.define(..., {
        requires: [],
        ...
    });
});
```

Alternatively/additionally adding support for anonymous classes, i.e.

```
Ext.define(null, {
    ...
});
```

would be provide support for a similar approach.

**Comment by dedesite** [comment]
Hello,

I submit a Pull request 9 days ago that fix this issue. Have you have time to review it ?

Thanks,
Andréas
